In [1]:
import numpy as np

In [8]:
a = np.array([[56, 0, 4.4, 68], [1.2, 104, 52, 8], [1.8, 135, 99, 0.9]])
print(a)
cal = a.sum(axis=0)
print(cal)
percentage = 100*a/cal
print(percentage)

[[  56.     0.     4.4   68. ]
 [   1.2  104.    52.     8. ]
 [   1.8  135.    99.     0.9]]
[  59.   239.   155.4   76.9]
[[ 94.91525424   0.           2.83140283  88.42652796]
 [  2.03389831  43.51464435  33.46203346  10.40312094]
 [  3.05084746  56.48535565  63.70656371   1.17035111]]


In [11]:
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
print(a+b)

a = np.array([[0,1,2], [3,4,5], [6,7,8]])
print(a)
b = np.reshape(np.array([1,2,3]), (3,1))
print(b)
print(a*b)

[[ 1.49239399  3.2175894   2.8995275 ]
 [ 0.2926616   0.01471114 -1.43823167]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1]
 [2]
 [3]]
[[ 0  1  2]
 [ 6  8 10]
 [18 21 24]]
